package solarsystemscalemodel.mithril

//A Mithril implementation of scalatags (based on the scalatags DOM implemention)
trait Tags extends scalatags.generic.Tags[MithrilBuilder, MithrilElement, MithrilNode] {

  // Root Element
  val html = "html".tag[MithrilElement]
  // Document Metadata
  val head = "head".tag[MithrilElement]
  val base = "base".voidTag[MithrilElement]
  val link = "link".voidTag[MithrilElement]
  val meta = "meta".voidTag[MithrilElement]
  // Scripting
  val script = "script".tag[MithrilElement]
  // Sections
  val body = "body".tag[MithrilElement]
  val h1 = "h1".tag[MithrilElement]
  val h2 = "h2".tag[MithrilElement]
  val h3 = "h3".tag[MithrilElement]
  val h4 = "h4".tag[MithrilElement]
  val h5 = "h5".tag[MithrilElement]
  val h6 = "h6".tag[MithrilElement]
  val header = "header".tag[MithrilElement]
  val footer = "footer".tag[MithrilElement]
  // Grouping content
  val p = "p".tag[MithrilElement]
  val hr = "hr".voidTag[MithrilElement]
  val pre = "pre".tag[MithrilElement]
  val blockquote = "blockquote".tag[MithrilElement]
  val ol = "ol".tag[MithrilElement]
  val ul = "ul".tag[MithrilElement]
  val li = "li".tag[MithrilElement]
  val dl = "dl".tag[MithrilElement]
  val dt = "dt".tag[MithrilElement]
  val dd = "dd".tag[MithrilElement]
  val figure = "figure".tag[MithrilElement]
  val figcaption = "figcaption".tag[MithrilElement]
  val div = "div".tag[MithrilElement]
  // Text-level semantics
  val a = "a".tag[MithrilElement]
  val em = "em".tag[MithrilElement]
  val strong = "strong".tag[MithrilElement]
  val small = "small".tag[MithrilElement]
  val s = "s".tag[MithrilElement]
  val cite = "cite".tag[MithrilElement]
  val code = "code".tag[MithrilElement]
  val sub = "sub".tag[MithrilElement]
  val sup = "sup".tag[MithrilElement]
  val i = "i".tag[MithrilElement]
  val b = "b".tag[MithrilElement]
  val u = "u".tag[MithrilElement]
  val span = "span".tag[MithrilElement]
  val br = "br".voidTag[MithrilElement]
  val wbr = "wbr".voidTag[MithrilElement]
  // Edits
  val ins = "ins".tag[MithrilElement]
  val del = "del".tag[MithrilElement]
  // Embedded content
  val img = "img".voidTag[MithrilElement]
  val iframe = "iframe".tag[MithrilElement]
  val embed = "embed".voidTag[MithrilElement]
  val `object` = "object".tag[MithrilElement]
  val param = "param".voidTag[MithrilElement]
  val video = "video".tag[MithrilElement]
  val audio = "audio".tag[MithrilElement]
  val source = "source".voidTag[MithrilElement]
  val track = "track".voidTag[MithrilElement]
  val canvas = "canvas".tag[MithrilElement]
  val map = "map".tag[MithrilElement]
  val area = "area".voidTag[MithrilElement]
  // Tabular data
  val table = "table".tag[MithrilElement]
  val caption = "caption".tag[MithrilElement]
  val colgroup = "colgroup".tag[MithrilElement]
  val col = "col".voidTag[MithrilElement]
  val tbody = "tbody".tag[MithrilElement]
  val thead = "thead".tag[MithrilElement]
  val tfoot = "tfoot".tag[MithrilElement]
  val tr = "tr".tag[MithrilElement]
  val td = "td".tag[MithrilElement]
  val th = "th".tag[MithrilElement]
  // Forms
  val form = "form".tag[MithrilElement]
  val fieldset = "fieldset".tag[MithrilElement]
  val legend = "legend".tag[MithrilElement]
  val label = "label".tag[MithrilElement]
  val input = "input".voidTag[MithrilElement]
  val button = "button".tag[MithrilElement]
  val select = "select".tag[MithrilElement]
  val datalist = "datalist".tag[MithrilElement]
  val optgroup = "optgroup".tag[MithrilElement]
  val option = "option".tag[MithrilElement]
  val textarea = "textarea".tag[MithrilElement]
}
